import type { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';
import axios from 'axios';
import Header from '../components/common/Header';
import Container from '../components/common/Container';
import List from '../components/common/List';
import Task from '../components/tasks/Task';
import { TaskType } from '../types/task/TaskType';
import { useEffect, useState } from 'react';
import { ApiModelResponse } from '../types/common/ApiModelResponse';
import { CreateTaskType } from '../types/task/CreateTaskType';
import Alert from '../components/common/Alert';
import { AlertType } from '../types/task/AlertType';

type HomeProps = {
  tasks: TaskType[]
}

const Home: NextPage<HomeProps> = ({ tasks: taskProps }) => {
  // const [tasks, setTasks] = useState<TaskType[]>([])
  // useEffect(() => {
  //   async function fetchData() {
  //     try {
  //       const fetchTasks = await axios.get<ApiModelResponse<TaskType[]>>('http://localhost:3333/tasks')
  //       setTasks([...fetchTasks.data.data])
  //     } catch (err) {
  //       console.log(err)
  //     }
  //   }
  // })
  const [url, setUrl] = useState<string>('')
  const [tasks, setTasks] = useState<TaskType[]>([])
  const [alert, setAlert] = useState<AlertType>({ msg: '', type: 'success', show: false })

  const getTaskList = async () => {
    console.log('getTaskList')
    try {
      const { data } = await axios.get('http://localhost:3333/tasks');
      setTasks([...data.data])
    } catch (err) {
      setAlert({ msg: "Erro ao listar as tasks.", type: 'error', show: true })
      console.error(err)
    }
  }

  const saveTask = async (task: CreateTaskType): Promise<void> => {
    // const url = 'http://localhost:3333/tasks'
    try {
      const res = await axios.post(url, task)
      await getTaskList()
      setAlert({ msg: "A task foi salva com sucesso.", type: 'success', show: true })
    } catch (err) {
      console.error(err)
      setAlert({ msg: "Erro ao salvar a task.", type: 'error', show: true })
    }
  }

  const checkTask = async (id?: string): Promise<void> => {
    const toggleTaskChecked = () => {
      const taskIndex = tasks.findIndex(task => task.id == id)
      tasks[taskIndex].checked = !tasks[taskIndex].checked
      setTasks([...tasks])
    }

    toggleTaskChecked()
    try {
      await axios.put(`${url}/check/${id}`)
    } catch (err) {
      toggleTaskChecked()
      console.error(err)
      setAlert({ msg: "Erro ao alterar a task.", type: 'error', show: true })
    }
  }

  const deleteTask = async (id?: string) => {
    try {
      const res = await axios.delete(`http://localhost:3333/tasks/${id}`)
      console.log(res)
      await getTaskList()
    } catch (err) {
      console.error(err)
      setAlert({ msg: "Erro ao deletar a task.", type: 'error', show: true })
    }
  }

  useEffect(() => {
    const fetch = async () => {
      await getTaskList()
    }
    const url = window.location.href.includes('localhost')
      ? 'http://localhost:3333/tasks'
      : 'https://e-task-list-backend.herokuapp.com/tasks'

    setUrl(url)
    fetch()
  }, [])

  return (
    <>
      <Head>
        <title>Task List</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header onSave={saveTask} />
      <Alert show={alert.show} msg={alert.msg} type={alert.type} toggleAlert={() => setAlert({ ...alert, show: false })} />
      <Container>
        <List>
          {tasks.map((task, i) => <Task task={task} onCheck={checkTask} onDelete={deleteTask} key={i} />)}
        </List>
      </Container>
    </>
  );
};

// export const getServerSideProps: GetServerSideProps = async (context) => {
//   const tasks = await axios.get('http://localhost:3333/tasks');
//   console.log(tasks.data.data);
//   return {
//     props: {
//       tasks: [...tasks.data.data],
//     },
//   };
// };

export default Home;
