import type {GetServerSideProps, NextPage} from 'next';
import Head from 'next/head';
import axios from 'axios';
import Header from '../components/common/Header';
import Container from '../components/common/Container';
import List from '../components/common/List';
import Task from '../components/tasks/Task';
import { TaskType } from '../types/task/TaskType';

type HomeProps = {
  tasks: TaskType[]
}

const Home: NextPage<HomeProps> = ({tasks}) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Container>
        <List>
          {tasks.map((task, i) => <Task task={task} key={i} />)}
        </List>
      </Container>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (context) => {
  const tasks = await axios.get('http://localhost:3333/tasks');
  console.log(tasks.data.data);
  return {
    props: {
      tasks: [...tasks.data.data],
    },
  };
};

export default Home;
